AllCops:
  Exclude:
    - config/**/**
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - spec/dummy/**/**
    - spec/**/**/**
    - gemfiles/**
    - db/**
    - bin/**

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented